name: Procesamiento de Datos y Creación de Datasets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pandas
    
    - name: Mostrar estructura de directorios
      run: |
        pwd
        ls -R
    
    - name: Ejecutar script de creación de datasets
      run: python pregunta.py
    
    - name: Verificar creación de archivos CSV
      run: |
        if [ -f train_dataset.csv ] && [ -f test_dataset.csv ]; then
          echo "Los archivos CSV se han creado correctamente."
          ls -l *.csv
        else
          echo "Error: No se encontraron los archivos CSV esperados."
          ls -l
          exit 1
        fi